# Generated by Django 4.1 on 2022-09-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('noticenum', models.AutoField(primary_key=True, serialize=False, verbose_name='공지글 번호')),
                ('admin', models.CharField(max_length=30, verbose_name='작성자')),
                ('noticetitle', models.CharField(max_length=1000, verbose_name='공지글 제목')),
                ('noticecontent', models.CharField(max_length=6000, verbose_name='공지글 내용')),
                ('noticedate', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
    ]
